language:
  - swift
osx_image: xcode10.1
script:
  - xcodebuild -project WKWebViewLocalAssets/WKWebViewLocalAssets.xcodeproj -scheme WKWebViewLocalAssets -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build | xcpretty